"""callback_added_in_message

Revision ID: 10d07db05f77
Revises: c96485398a2b
Create Date: 2025-11-18 18:00:35.668633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d07db05f77'
down_revision: Union[str, Sequence[str], None] = 'c96485398a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('callback_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'callback_text')
    # ### end Alembic commands ###
