"""date__events

Revision ID: d8fe88eb4dd4
Revises: deb9a2c18912
Create Date: 2025-11-20 15:41:14.109653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fe88eb4dd4'
down_revision: Union[str, Sequence[str], None] = 'deb9a2c18912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
